mat4.multiply=function(a,b,c){
    c||(c=a);
    var d=a[0],
    e=a[1],
    g=a[2],
    f=a[3],
    h=a[4],
    i=a[5],
    j=a[6],
    k=a[7],
    l=a[8],
    o=a[9],
    m=a[10],
    n=a[11],
    p=a[12],
    r=a[13],
    s=a[14];
    a=a[15];
    var A=b[0],
    B=b[1],
    t=b[2],
    u=b[3],
    v=b[4],
    w=b[5],
    x=b[6],
    y=b[7],
    z=b[8],
    C=b[9],
    D=b[10],
    E=b[11],
    q=b[12],
    F=b[13],
    G=b[14];
    b=b[15];
    c[0]=A*d+B*h+t*l+u*p; // a0*b0 + a4*b1 + a8*b2 + a12*b3
    c[1]=A*e+B*i+t*o+u*r; // a1*b0 + a5*b1 + a9*b2 + a13*b3
    c[2]=A*g+B*j+t*m+u*s;
    c[3]=A*f+B*k+t*n+u*a;
    c[4]=v*d+w*h+x*l+y*p;
    c[5]=v*e+w*i+x*o+y*r;
    c[6]=v*g+w*j+x*m+y*s;
    c[7]=v*f+w*k+x*n+y*a;
    c[8]=z*d+C*h+D*l+E*p;
    c[9]=z*e+C*i+D*o+E*r;
    c[10]=z*g+C*j+D*m+E*s;
    c[11]=z*f+C*k+D*n+E*a;
    c[12]=q*d+F*h+G*l+b*p;
    c[13]=q*e+F*i+G*o+b*r;
    c[14]=q*g+F*j+G*m+b*s;
    c[15]=q*f+F*k+G*n+b*a;return c}